# Generated by Django 4.2.6 on 2023-11-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_rename_completed_task_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_completed',
            new_name='completed',
        ),
    ]
