# Generated by Django 4.2.6 on 2023-11-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_rename_task_completed_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
    ]
