# Generated by Django 4.2.6 on 2023-11-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_alter_task_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_posted']},
        ),
    ]
