# Generated by Django 4.2.6 on 2023-12-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
